# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

# url: http://localhost:4000
title: Afghanistan Survey Data
description: An open-source open data platform for analyzing and visualizing Democracy International public opinion research findings in Afghanistan.
author:
  name: mbaldassaro
  email: mbaldassaro@gmail.com

# Grunt handles images and assets.
exclude: ['y', 'y', 'y', 'y',
          '**.gif', '**.webp']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
permalink: pretty
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

social:
  - title: twitter
    url: https://twitter.com/democracyintl
  - title: facebook
    url: https://www.facebook.com/DemocracyInternational
  - title: linkedin
    url:

pygments: false
